### ISSUE TITLE
Selecting Two Fields from Configured 8 for Monitoring Case in NANS3-AAAZ30AN1 Sensor without Safety Designer

### ISSUE THREAD

**Issue by miksiWan** [SICKAG/sick_safetyscanners_base#31]
Hello

I'm using the NANS3-AAAZ30AN1 model sensor. I have configured 8 fields and 2 monitoring cases using Safety Designer. 
How can I set which 2 of the 8 fields should be used for the Monitoring Case while the sensor is operational on the robot?

**Comment by lenpuc** [comment]
Hello,
the safety-related configurations need to be configured in the safety Designer. It is possible to trigger changes using the sensor's IOs. However, all this logic needs to be implemented in the safety designer. The driver here can only read which fields are active since the API does not allow safety-related changes from software.
